name: Deploy VitePress

on:
  push:
    branches:
      - master # 仅当 main 分支有变更时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # https://github.com/marketplace/actions/checkout

      - name: Setup Node.js
        uses: actions/setup-node@v4 # https://github.com/marketplace/actions/setup-node-js-environment
        with:
          node-version: '22.10.0' # 选择与项目兼容的 Node 版本

      - name: Install pnpm
        run: npm install -g pnpm # 全局安装 pnpm

      - name: Install dependencies
        run: pnpm install # 使用 pnpm 安装依赖

      - name: Build VitePress
        run: pnpm run docs:build # 确保 package.json 中有 "docs:build" 脚本，通常为 "vitepress build docs"

      - name: List files
        run: ls -la ./.vitepress/dist # 增加调试命令，查看是否生成了 dist文件

      - name: Check if dist directory exists # 检查内容是否存在
        run: |
          if [ -d ./.vitepress/dist ]; then
            echo "文件存在"
          else
            echo "不存在......"
            exit 1  # 如果目录不存在，失败此步骤
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # https://github.com/marketplace/actions/github-pages-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./.vitepress/dist
